### ISSUE TITLE
Error when following example q.toArray is not a function

### ISSUE THREAD

**Issue by guimard** [danieloneill/nodedbi#3]
Hi,
I've this error hen following this example with sqlite3

**Comment by danieloneill** [comment]
Hi there. Directly above the example code is the link to the convenience methods:

[https://gist.github.com/danieloneill/2605640f020c89fb806a]

It's not strictly part of the package but I've considered adding them to the basic index.js at some point.

**Comment by guimard** [comment]
OK, thank you !
